# Default, Defaults
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Artist Theme
email: your-email@domain.com
description: A small and simple site I made to test out Jekyll. Watch out! I'm going to make a material design theme next!
baseurl: "https://sunchengbo321.github.io/DreamSkii" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: "https://sunchengbo321.github.io/DreamSkii"
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter:
facebook:
google:

author: Nina Petropoulos
authorBio: A Landingguy dreaming of swimming in the sky  
