# Default, Defaults
markdown: kramdown
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Orange & Magic 
email: your-email@domain.com
description: A small and simple site I made to test out Jekyll. Watch out! I'm going to make a material design theme next!
baseurl: "https://sunchengbo321.github.io/DreamSkii" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: "https://sunchengbo321.github.io/DreamSkii"
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter:
facebook:
google: 
github:https://github.com/Sunchengbo321

author: Emmmbeeed
authorBio: A Landing Guy Dreaming of Swimming in the Sky  
